{% set name = "gputools" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dc3a4aef73e802f6b94a4262ac4c637a2fb62fe8472368e9143248d6d1cb93de

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - reikna
    - six
    - scipy
    - numpy >=1.11.0
    - pyopencl >=2016.1
    - configparser

test:
  requires:
    - pip
    - pocl  >=0.14  # [linux or osx]
    - oclgrind  # [win]
    - python {{ python_min }}
  imports:
    - gputools
  commands:
    - pip check

about:
  home: https://github.com/maweigert/gputools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: GPU accelerated image/volume processing in Python

extra:
  recipe-maintainers:
    - maweigert
    - tlambert03
